### ISSUE TITLE
__version__ missing

### ISSUE THREAD

**Issue by buhtz** [karlicoss/orgparse#68]
Not sure but it seems that there is no version information available.

    >>> import orgparse
    >>> orgparse.__version__
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    AttributeError: module 'orgparse' has no attribute '__version__'

I do use `0.4.20231004` from PyPi install via `pip`.

**Comment by karlicoss** [comment]
Sorry, just noticed it! I think I removed it when I switched to semantic versioning generated from git tag information -- maintinaing a version manually in the source code is kind of annoying.
You can get installed version with `importlib.metadata.version("orgparse")` (and that works with any package!) https://docs.python.org/3/library/importlib.metadata.html#overview -- does that work for you?

**Comment by buhtz** [comment]
Thank you for your reply.
Having `__version__` doesn't mean to fill this variable with a static value. See [this example](https://codeberg.org/buhtz/hyperorg/src/commit/a814c4bf5e95bd522fabe66d7baed9d71a7090e9/src/hyperorg/__init__.py#L62) of one of my own projects how you can generate such data based on the packages meta data.

**Comment by karlicoss** [comment]
Hey, sorry again for being away!

Fair enough that you can fill it dynamically, but then what's the benefit of having it in orgparse if whoever needs it can just use `importlib.metadata.version("orgparse")` themselves? 

Having `__version__` might make sense for some libraries if they are vendored in some esoteric way and not pip installed, but then setting it dynamically wouldn't work either.

What's your usecase? In particular, in the context of `orgparse`?

**Comment by buhtz** [comment]
The use case is to check the value of `__version__` which is the usual way in Python packages. For example to create diagnostic data for my own application I need to know which versions the depending packages are on.

And this don't work
```py
>>> import importlib
>>> importlib.metadata.version("orgparse")
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    importlib.metadata.version("orgparse")
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'metadata'
```
Even if it would work I experience it as a workaround not as a solution. I need to import another package just to get the version of another one?

**Comment by karlicoss** [comment]
> And this don't work

It works, just need to import correctly
```
[i]>>> import importlib.metadata
[i]>>> importlib.metadata.version('orgparse')
'0.4.20231004'
```

> which is the usual way in Python packages

I wouldn't say it's the usual way -- it never became a proper standard, so you can't really rely on it being present (evidently as we're discussing it here :) )

E.g. see a lengthy discussion here https://discuss.python.org/t/please-make-package-version-go-away/58501

The main concerns with `importlib.metadata` there are cases when package is vendored/not properly installed, so `importlib.metadata` won't work for that. But in that case the snippet you linked which you use to set `__version__` won't work either! 

What's worse, in such cases it would crash at import time (since it's a global attribute), so the package will break for all users, not just the ones who care about the version (a very very small minority).

> I need to import another package just to get the version of another one?

I mean, yes? I'd understand your concern if it was some external package, but this is something from stdlib, just two lines of code and works in the vast majority of cases, not just for packages that have `__version__` set.
